canonical/operator-libs-linux

lib/charms/operator_libs_linux/v0/apt.py, tests/test_repo.py, tests/test_snap.py
For options other than `signed-by`, parse them out into a dict so we they can be set appropriate and we don't fail. There's a surprisingly long list of options here, and while most are not relevant enough to expose, we shouldn't fail, either.
Don't raise `InvalidSourceError` unless the entire file fails to parse. This didn't come up in development since the LXD 20;04 image also has all comments stripped out of `sources.list` files.
=> Fix up parsing more complex sources..list lines

lib/charms/operator_libs_linux/v0/snap.py, tests/test_snap.py
Throw a `SnapError` if `snapd` isn't installed, to provide more
meaningful feedback to users.
`snapd` does not always populate the catalog in
`/var/cache/snapd/names` at install time, especially if it's
installed/started as part of `cloud-init`, in a container, or
somewhere else where networking may not be available at first
run.
The snapd API doesn't provide a convenient way to refresh this,
and restarting the service is undesirable. Instead, if a requested
package isn't in the cache, blindly try the `snap` API to see if
we can fetch info for the requested package and return a
`SnapNotFoundError` if we get a `SnapAPIError`
=> Check whether snap is installed at all, and catalog presence

lib/charms/operator_libs_linux/v0/apt.py, tests/test_repo.py
The functions cribbed from charmhelpers assume subprocess.Popen
communication, and there are better semantics in 3.5+ with run().
Convert to use those instead
=> Fix GPG key handling

lib/charms/operator_libs_linux/v0/systemd.py, tests/unit/test_systemd.py
As title suggests, this makes some internal details 'private' by prefixing their name with `_`.
Fixes #26
=> Make service and popen_kwargs 'private'; driveby spelling fix

lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v0/snap.py
A trivial change to add missing closing bracket in the `apt.py` docstring, and update logging formatting in the `snap.py` docstring to match guidelines per https://juju.is/docs/sdk/styleguide#heading--logging.
=> Add missing closing bracket from apt docstring, and update logging formatting in snap docstring to match guidelines

.github/workflows/ci.yaml, lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v0/snap.py, tests/integration/test_apt.py, tests/integration/test_passwd.py, tests/integration/test_snap.py, tests/unit/fake_snapd.py, tests/unit/test_repo.py, tox.ini
This PR enables the support for Python 3.5 by introducing the following changes:
- Change f-strings (from Python 3.6+) to str.format().
- Change the pyfakefs to the latest version that supports Python 3.5.
- Add the same Python versions from OF CI to this repo CI. 
- Sort options dict in order to have a consistent order in Python 3.5.
Python 3.5 support is important in order to create charms like the new Postgres Machine Charm and continue to support Xenial (which uses Python 3.5).
=> Add support for Python 3.5

lib/charms/operator_libs_linux/v0/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
Addresses gh#9
This was meant to be a quick "dive in a fix it."
We haven't actually implemented refresh, however, which means that
there is more work to do.
Next steps are to add enough code to fix the failing tests, while giving
some thought to how refresh should flow through the library in general.
=> Added snap cohorts

lib/charms/operator_libs_linux/v0/apt.py, tests/unit/test_apt.py
This PR adds an additional check in the `apt` library when looking for an installed package (via `dpkg`) and in the `apt-cache`. It avoids returning a `PackageNotFoundError` when there is a package with `all` architecture, like the `postgres` package (in contrast to `postgresql-12` package and others, which are listed with specific architectures like, for example, `amd64`).
=> Add check for 'all' architecture

lib/charms/operator_libs_linux/v1/snap.py
Snapd updates the `/var/cache/snapd/names` cache file infrequently and it
is normal for it to be not present.  Because this is a normal condition
of operation, the relevant warnings have been removed.
Fixes #34.
=> remove warnings for missing snap cache data

lib/charms/operator_libs_linux/v0/apt.py
This method actually raises TypeErrors and PackageErrors, depending on behaviour. This PR adds this information to the docstring.
=> Updated "Raises" section in add_package() docstring to match method.

lib/charms/operator_libs_linux/v1/snap.py, pyproject.toml, tests/integration/test_snap.py, tests/unit/test_snap.py
- Add daemon service management functionality within `snapctl` alongside a `Snap` instance, keeping it contained with the popular `Snap` instance for charming
- feat: add `start`, `stop`, `logs`, `restart` methods to `Snap` object (matching `snapctl`)
- Methods can take a `list`,`str` or None services, evaluating to `snap start lxd.activate lxd.user-daemon`, `snap start lxd.user-daemon` or `snap start lxd`
- These are called by `Snap._snap_daemons()` which (attempts) to ensure that a given snap instance can only launch services containing it's own `_name`
- feat: add `Snap.services`, `Snap.apps` properties to get metadata from the API for installed snaps
- `Snap.apps` looks like `{"snap":"charmcraft","name":"charmcraft"},{"snap":"juju","name":"fetch-oci","daemon":"oneshot","daemon-scope":" …
=> feat: add service management functionality to snap.py

lib/charms/operator_libs_linux/v1/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py, tox.ini
The feature to hold an individual snap is not yet in snapd, but this allows a charm author to hold snap refreshes system-wide
=> Adds ability to hold snap refreshes system wide

lib/charms/operator_libs_linux/v1/snap.py, tests/unit/test_snap.py
There were two issues with the module level function install_local() that needed adressing.
- The unused function parameter: `self`
- Some combinations of the function parameters `classic` and `dangerous` ended up in passing empty arguments to the `snap` process when called with subprocess.check_output(), which it did not really like.
Fixes: #49
Signed-off-by: Mert Kırpıcı <mert.kirpici@canonical.com>
=> snap: remove empty args from check_output

lib/charms/operator_libs_linux/v0/passwd.py, pyproject.toml, tests/unit/test_passwd.py
The `--system` argument needs also `--create-home` argument to be present for the creation of home directory for system users.
This change adds a new parameter to the `add_user` function signature, called `create_home` which defaults to True to provide backwards compatibility with the current api. After this change, home directory will be always created regardless of regular users or system users unless False is passed for `create_home`.
=> passwd: create home dir for system users

.github/workflows/ci.yaml, lib/charms/operator_libs_linux/v1/snap.py, tests/unit/test_snap.py, tox.ini
Pull request contains fixes for the snap charm library's `install_local` method. Here is what I changed:
1. On `subprocess.check_output(...).splitlines()`, I changed the selected index from 0 to -1.
2. I added a regular expression that filters ANSI characters out from the captured `snap_name` so that the API request to the snapd socket does not fail.
Closes: #54, #55
=> Fix snap charmlib's `install_local` method

.github/workflows/ci.yaml, lib/charms/operator_libs_linux/v0/apt.py, tests/unit/test_apt.py, tests/unit/test_snap.py, tox.ini
```bash
lxc launch ubuntu:xenial xenial
lxc exec xenial wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec xenial python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<...>
apt.PackageError: Could not install package(s) [['python3-pymongo=3.2-1build1']]: None
```
❌
```bash
lxc launch ubuntu:bionic bionic
lxc exec bionic wget https://raw.githubusercontent.com/canonical/operator-libs-linux/main/lib/charms/operator_libs_linux/v0/apt.py
lxc exec bionic python3
```
```python
import apt
apt.update()
apt.add_package(['python3-pymongo'])
<...>
apt.PackageError: Could not install package(s) [['python3-pymongo=3.6.1+dfsg1-1']]: None
```
❌
```bash
lxc launch ubuntu:focal focal
lxc exec focal wget …
```
=> fix: inherit environment before adding new keys

lib/charms/operator_libs_linux/v0/apt.py, tests/unit/test_snap.py, tests/unit/test_systemd.py
This PR allows users to import a key without a dummy `DebianRepository` instance, by adding a top-level `import_key` function that does the work, and then refactoring `DebianRepository.import_key` to use this. Users that want to import a key but don't have a `DebianRepository` can just call the new top-level function.
=> Make import_key a stand-alone function for use with a DebianRepository

lib/charms/operator_libs_linux/v0/passwd.py, lib/charms/operator_libs_linux/v1/systemd.py
These had been modified (systemd only with comment changes, but still) in previous PRs but LIBPATCH hadn't been bumped, so `charmhub publish-lib` was complaining that the content was different.
=> Bump LIBPATCH for two libraries that had been modified but not bumped

.github/workflows/ci.yaml, lib/charms/operator_libs_linux/v0/dnf.py, tests/integration/test_dnf.py, tests/unit/test_dnf.py, tox.ini
This pull request aims to add a dnf charm library offering to the operator_libs_linux collection of charm libraries. The dnf library will be used for charms that need to support both Ubuntu and RPM-based distributions (CentOS, Alma, etc.), as well as charms just intended to be deployed to just RPM-based Juju units. It comes with the standard bells and whistles needed to interact with dnf from a simple Python interface.
Documentation and registering the library on Charmhub. This pull request is mostly focused on just adding the initial code for a dnf charm library; do not want too many themes in the pull request review.
* I updated the version of the `setup-lxd` GitHub Action to 0.1.0 instead of just using a commit hash. I also set the channel of LXD to 5.9/stable
* I am using the …
=> feat: add dnf charm library

charmcraft.yaml, metadata.yaml, requirements.txt
These are machine-charm utilities, so make the placeholder charm a machine charm so it shows up correctly in Charmhub. Do this by removing containers / resources from metadata.yaml.
Also:
- Update Ubuntu version to 22.04 (not that it matters for charm libs)
- Don't need to be on the latest master "ops", just use latest release
Fixes #47
=> fix: make placeholder charm a machine charm

lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/operator_libs_linux/v1/systemd.py, pyproject.toml, tests/integration/test_snap.py, tests/unit/test_snap.py, tests/unit/test_systemd.py, tox.ini
There looks like there are lots of changes here, but the key is:
- Update from black/isort -> black/ruff
- Introduce codespell
Then there are a bunch of changes to docstrings and spellings to conform to ruff's rules. Main change is making first line of docstrings use the imperative mood.
Fixes #77
=> build: update to use ruff/codespell

.github/workflows/build-and-test.yaml, .github/workflows/pull-request.yaml, .github/workflows/release-libs.yaml, .github/workflows/release.yaml, lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v1/snap.py, lib/charms/operator_libs_linux/v1/systemd.py
This PR makes a few key changes to our CI:
- Use `ubuntu-22.04` everywhere rather than `ubuntu-20.04`
- Use concurrency controls to prevent unnecessary runs
- Don't duplicate runs for PRs (previously we triggered on `push` and `pull-request` without constraint)
- Release charm to edge on merge to main, and a relevant path was updated
- Release charm libs when changed automatically
Fixes #71
=> ci: restructure CI; include release charm and lib action

lib/charms/operator_libs_linux/v1/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
Based on the feedback on #80, adds an option to hold the refresh of snaps forever.
=> feat: add forever hold to snap refresh.hold

lib/charms/operator_libs_linux/v1/snap.py
If an empty string is passed as as the channel during refreshing (ala `'snap refresh foo --channel="{}"'.format("")`, it simply parses out to an empty string.
This makes snap/subprocess bomb, because `["snap", "refresh", "foo", ""]` gives a pleasant result, like:
```
File "./src/charm.py", line 181, in on_install                                                                         
self.snap.ensure(state=snap.SnapState.Latest)                                                                        
File "/var/lib/juju/agents/unit-grafana-agent-12/charm/lib/charms/operator_libs_linux/v1/snap.py", line 504, in ensure 
self._refresh(channel, cohort)                                                                                       
File …
```
=> Do not set a `--channel` arg if it's not truthy

lib/charms/operator_libs_linux/v1/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
We are now able to install snaps by revisions, but the snap charm library does not yet support this flag.
We would like to add support for the `--revision` flag so that we can pin our snap versions in charms.
Add optional kwarg `revision` to the `ensure`, `_install` and `_refresh` methods of Snap in the snap charm lib
=> feat: install snap by revision

.github/workflows/build-and-test.yaml
There is a bug in canonical/setup-lxd@v0.1.0 where the `channel` input is ignored. This has been fixed in v0.1.1. See https://github.com/canonical/setup-lxd/pull/8
=> update canonical/setup-lxd to v0.1.1

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
Fix #91
Snap revisions can be strings and should be handled as strings
=> fix(snap): handle revision as str

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_dnf.py, tests/integration/test_snap.py, tests/unit/test_snap.py
We would like to be able to create snap aliases using the charm library
Add `alias` method to create aliases.
=> feat: create alias for a snap

lib/charms/operator_libs_linux/v0/sysctl.py, tests/integration/test_sysctl.py, tests/unit/test_sysctl.py
PoC integration with Kafka: https://github.com/canonical/kafka-operator/pull/118
Addresses [DPE-2111](https://warthogs.atlassian.net/browse/DPE-2111)
This draft will be updated with feedback from #98 and Kafka PR before setting it to ready to review.
[DPE-2111]: https://warthogs.atlassian.net/browse/DPE-2111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Sysctl init

lib/charms/operator_libs_linux/v0/sysctl.py, tests/integration/test_sysctl.py, tests/unit/test_sysctl.py
Fixes docstring to have correct exception naming.
=> Fix error naming example

lib/charms/operator_libs_linux/v0/sysctl.py, tests/unit/test_sysctl.py
Some file operations were not correctly coded, and were failing silently. Thanks @rgildein for reporting this!
=> Fix file operations in unit tests

lib/charms/operator_libs_linux/v1/systemd.py, tests/integration/test_systemd.py, tests/unit/test_systemd.py
Hello - this pull request extends the service methods in the systemd charm library to now accept multiple arguments. I made this change so that when charm authors need to pass extra parameters to `systemctl`, they do not need to directly call the private `_systemctl` method and can instead pass the extra arguments to via the public `service_*` methods.
For example, say you have a service that takes several seconds to start. Using `service_start(...)` in its currently implementation will cause Python to block until systemctl returns an exit code (`Popen.wait()`). This is inconvenient especially if you have a service that could take 30+ seconds to start. With the implementation this pull request proposes, you can pass the `--no-block` option to `service_start(...)` and let the charm …
=> Enable systemd service methods to accept multiple args

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
This patches added a `use_json` optional arguments to `Snap.get` and `Snap.set` so that the two methods can make use of the built-in types in Python while setting / getting snap configurations. 
The new option allows snap config options to be compared more natively, for example:
```python
s = snap.SnapCache()["some-snap"]
s.set({"foo": True}, use_json=True)
assert s.get("foo", use_json=True) # instead of == "True"
```
Although the required argument for the two methods did not change, the behaviour still differs a bit when setting `use_json=True`. Therefore,  the default `use_json` is set to `False` for backward compatibility. 
Fixes: #107
=> Allow `Snap.get` and `Snap.set` to respect the Python's built-in types

lib/charms/operator_libs_linux/v2/snap.py
Increase default SnapClient timeout to 30 seconds
SnapClient has a default timeout of 5 seconds for all RPCs to
the snapd socket. If any operation takes more, an exception is
raised to the caller.
We have seen this causing issues in slow CI environments, where
a simple config-changed hook will attempt to check if a snap is
installed, timeout and move the unit to a blocked status (causing
the CI run to fail). This is augmented by the fact that typically
SnapCache is used instead of SnapClient, which only uses the default
value and does not provide a way to configure the timeout.
Simply increasing the timeout is enough to tackle the flakes.
A possible alternative could be to surface the timeout option to SnapCache,
but that then would require each consumer of the library to set the timeout.
=> Increase default SnapClient timeout to 30 seconds

README.md
Add badges for the Github workflows (except PR checks) to the README.
These will show when viewing the README in a markdown reader that loads external images (e.g. on GitHub itself) but more importantly also show the CI status on [the Juju releases page](https://releases.juju.is/).
=> docs: add workflow badges to the README

lib/charms/operator_libs_linux/v0/apt.py, tests/unit/test_apt.py
It's inadvisable to use `check_call` with `stdout=PIPE` and `stderr=PIPE`, as the child process will block if enough output is generated (see Note in https://docs.python.org/3/library/subprocess.html#subprocess.check_call)
We've seen some hanging subprocesses in the `landscape-server` charm due to this (and other, already addressed issues): https://bugs.launchpad.net/landscape/+bug/2033091
This change uses `subprocess.run` instead, with `capture_output=True` and `check=True`. Behaviour should be the same, except avoiding the aforementioned blocking issue.
=> apt.py: use subprocess.run with check=True instead of check_call when capturing stdout and stderr

lib/charms/operator_libs_linux/v0/apt.py, tests/integration/test_apt.py, tests/unit/test_apt.py
as mentioned in #114 , this patch changes some select `PackageError` exceptions to consume `CalledProcessError.stderr` instead of `CalledProcessError.output` (an alias for `stdout`).
These exceptions should now actually contain the error output of the subprocesses with non-zero exit codes.
=> apt.py: use CalledProcessError.stderr in exceptions instead of output/stdout

lib/charms/operator_libs_linux/v2/snap.py, tests/unit/test_snap.py
Snaps have [3 confinement levels](https://snapcraft.io/docs/snap-confinement): strict, classic and devmode. devmode snaps are useful during the development process.  Here we add support for installing snaps with the devmode level of confinement.
The first reason to add support for devmode is by symmetry with snaps/snapcraft. `devmode` is supported by snapcraft.io, why not support it here?
The second reason is pragmatic. The telco team has the SD-Core UPF charm which is only available in devmode. Adding strict confinement for this charm [won't be straightforward](https://github.com/canonical/sdcore-upf-snap/issues/2) but we don't want to go through the "classic" review process until we really had a try with strict confinement for it. Until then it will only be available in devmode and we …
=> feat(snap): add support for devmode confinement

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py
Add log messages to signal snap installation/refresh steps, so the user can check how long it took.
Motivated by https://warthogs.atlassian.net/browse/DPE-3845
=> Add logging to snap install steps

.github/workflows/build-and-test.yaml, pyproject.toml, tests/unit/test_sysctl.py, tox.ini
While testing with python3.12, i had to bump `pyfakefs==5.5.0` due to some changes in `pathlib`
After this adjustment, i found bad tests in `test_sysctl`. 
instead of 
```python
assert my_mock.called_with(...)
```
swapped to 
```python
my_mock.assert_called_once_with(...)
```
Also, it seems codespell now doesn't like `assertIn` so let's start ignoring reasonable words
=> Adjustments to test with python 3.12

lib/charms/operator_libs_linux/v2/snap.py, tests/unit/test_snap.py
Addresses issue #120 
`snap refresh --revision=xyz` causes snapd to restart the service provided by that snap, even if the revision is already on the machine. In this limited case, we should not refresh the snap if it is already on the correct revision.
=> Prevent refresh by revision when the snap is already on that revision

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py
Fix snap.get method to handle the case where the key is falsy. Treat it as no key provided, which results in the expected behavior to get all values from snap configs.
Fix #124
=> snap.py: fix snap.get optional key

lib/charms/operator_libs_linux/v0/juju_systemd_notices.py, tests/integration/juju_systemd_notices/notices-charm/actions.yaml, tests/integration/juju_systemd_notices/notices-charm/charmcraft.yaml, tests/integration/juju_systemd_notices/notices-charm/metadata.yaml, tests/integration/juju_systemd_notices/notices-charm/src/charm.py, tests/unit/test_juju_systemd_notices.py, tox.ini
Fixes #126 
This pull request enables support for observing snap services using the `juju-systemd-notices` charm library.
The key change in this pull request is modifying how the notices daemon configures how it observes services on the machine. Rather than configure which services to observe by reading the `hooks` directory, the daemon instead reads a _watch.yaml_ file in the charm directory. Here's what the _watch.yaml_ file would look like in a deployed charm using the notices daemon:
```yaml
---
snap.slurm.slurmd: slurmd
snap.slurm.munged: munged
```
Originally, `juju-systemd-notices` used a regex that parsed hook names to determine which services to observe with the notices daemon. This approach worked until we needed to start working with nested services - e.g. have `.` in the …
=> feat: enable juju-systemd-notices to observe snap services

lib/charms/operator_libs_linux/v0/apt.py, tests/unit/test_apt.py
In scripting apt operations, adding `--error-on=any` to `apt-get update` is necessary to capture erros like "Some index files failed to download". Otherwise, charms move onto package installations with a stale index.
equivalent to: https://github.com/juju/charm-helpers/pull/911
ref: https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1693900
=> Fail and retry on "Some index files failed to download"

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
Use the snapd REST API to change snap configurations instead of using the `snap` command.
This improves security in case a secret in command line arguments are logged.
=> Use snapd REST api to change snap config

lib/charms/operator_libs_linux/v2/snap.py, tests/unit/test_snap.py
This PR fixes the issue #139 .
The task status can be `Do` and should not be considered an error ([see here](https://snapcraft.io/docs/snapd-rest-api#heading--changes) in the subsection 'Task Fields').
This status means that the task is ready to start but hasn't started yet.
I have added a case in the unit testing of the SnapClient.
=> fix: Task status can be `Do` and should not raise an error.

tests/integration/test_snap.py
One test, `test_snap_set_and_get_with_typed`, often [fails](https://github.com/canonical/operator-libs-linux/actions/runs/12043896518/job/33580021129) -- maybe 50% of the time. It fails when trying to ensure that the `lxd` snap is present on the latest version, raising a `SnapError` with the  message 'Waiting for "snap.lxd.daemon.service" to stop'.
The existing code catches this once, waits 60 seconds and retries. Since the test often passes, this must sometimes be sufficient, so this PR simply uses slightly more robust retry logic -- retrying up to 10 times with 20 seconds in between each attempt. In [5/5 CI runs](https://github.com/james-garner-canonical/operator-libs-linux/actions/runs/12643899480/job/35232205555?pr=4), this passed every time .
As a future CI improvement, it would be …
=> tests: fix flaky snap test by adding multiple retries

.github/workflows/build-and-test.yaml
This PR updates the `build-and-test` workflow to run on `ubuntu-latest` instead of `ubuntu-22.04`, following `ops`.
It also bumps the versions on the `checkout` and `setup-python` actions accordingly, and pins the `tox` version following `ops`.
For the integration tests, which require running `tox` as `root`, we install `tox` via `apt`.
Also bump the `juju` version from `3.1` to `3.6` since it's the LTS release.
=> ci: use ubuntu-latest; bump checkout and python versions (following ops)

lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v0/sysctl.py, lib/charms/operator_libs_linux/v2/snap.py, pyproject.toml, tests/integration/test_sysctl.py, tests/unit/fake_snapd.py, tests/unit/test_dnf.py, tests/unit/test_grub.py, tests/unit/test_snap.py, tests/unit/test_systemd.py, tox.ini
This PR updates `tox.ini` to use `ruff --preview` for all linting and formatting (dropping `black`), and have `codespell` run correctly, updating `pyproject.toml` accordingly.
The core of the PR is the changes to `tox.ini` and `pyproject.toml`. The linting rules for `ruff` have been updated to include all the rules that `ops` uses. To allow linting to continue to pass, any rules that are currently broken in a single file are ignored for that file, while rules that are broken in multiple files are ignored globally. These ignores are marked with a `FIXME` to distinguish them from intentional ignores that are copied from `ops`.
Changes to other files are either from `ruff format` or from `codespell`. There are typo corrections and a couple of small formatting changes to libraries, which are …
=> ci: update linting (following ops)

lib/charms/operator_libs_linux/v2/snap.py, pyproject.toml, tests/integration/juju_systemd_notices/notices-charm/src/charm.py, tests/unit/test_snap.py
This PR disables all the "FIXME" linting rules affecting snap.py, updating snap.py to pass linting. One change required an update to test_snap.py as well. Globally disabled "FIXME" linting rules have all been moved to per-file ignores to make it easy to see what needs fixing for each individual lib or test suite. The ruff linting config now also selects flake8-logging-format (G) to ensure that calls to logging use deferred message evaluation.
I think the file view is pretty readable, if a bit long. The commit view might be clearer, though some later commits supersede the changes made in earlier commits (e.g. f-strings commit changes were modified by the later line-length changes).
=> ci: remove linting ignores for snap.py

lib/charms/operator_libs_linux/v2/snap.py
This PR just bumps `LIBPATCH` to trigger a release of the `snap` lib, which should have been done in the last PR finalising the linting and typing changes for this library.
=> chore: bump LIBPATCH to release the snap library

lib/charms/operator_libs_linux/v0/apt.py
The PR updates the `apt` library to use futurised type annotations. This will make it easier to read the diff for the next PR, which will update type annotations for this library to pass pyright's type checking. `LIBPATCH` will be incremented once this batch of PRs for the `apt` library are completed.
=> style: use type annotations from the future (for apt.py)

lib/charms/operator_libs_linux/v0/apt.py, tox.ini
Enable static analysis of `apt.py` in ci. `LIBPATCH` will be bumped after one more follow up PR handling `ruff` linting for this lib.
=> style: update type hints and enable type checking in ci for apt.py

lib/charms/operator_libs_linux/v0/apt.py, pyproject.toml, tox.ini
This PR removes the linting ignores for apt.py and fixes each resulting problem. Commit view may be helpful as one ignore is fixed in each commit, but the file view is pretty straightforward.
=> style: remove linting ignores for apt.py

lib/charms/operator_libs_linux/v0/apt.py
Let's release the apt library with its improved typing before the pulse report.
=> chore: bump apt.py LIBPATCH for release

.github/workflows/build-and-test.yaml
This PR just adds `workflow_dispatch` to the tests so that they can be run manually for debugging purposes.
=> ci: add workflow_dispatch to tests for debugging flaky tests

tests/integration/test_apt.py
Known issue on hardware-observer-operator, this PR just copies the pending fix to our test:
- https://github.com/canonical/hardware-observer-operator/issues/414
- https://github.com/canonical/hardware-observer-operator/pull/415
=> tests: fix failing integration test

lib/charms/operator_libs_linux/v2/snap.py, tests/integration/test_snap.py, tests/unit/test_snap.py
When a `SnapError` is raised after a `snap` command errors (raising a `CalledProcessError`), the error does not currently contain the process's `stderr`. Additionally, the failure information may not be present in `stdout` or `stderr`, but may instead have been logged to the journal. This PR updates the 6 call sites where a `CalledProcessError` is converted to a `SnapError` as follows:
- The `subprocess` call is updated to always capture `stdout` and `stderr` so that these are available in the `CalledProcessError`
- The specific error message and the `CalledProcessError` are passed to a new constructor for `SnapError`
- `SnapError._from_called_process_error` extends the provided message with `stdout` and `stderr` from the `CalledProcessError`, and attempts to extend it further with the …
=> feat: improve logging on snap error

lib/charms/operator_libs_linux/v0/apt.py, lib/charms/operator_libs_linux/v2/snap.py
This PR updates the `apt` and `snap` library docstrings to prominently feature a deprecation notice. `LIBPATCH` is bumped to release to libraries so that users have a chance of seeing the deprecation notice.
The test failure is unrelated.
=> docs: update docstrings of apt and snap libs with deprecation notice
